#!/usr/bin/env zsh

pushd $DOTFILES

echo "Ensure default .zshrc and .zprofile are removed"
rm ~/.zshrc ~/.zprofile

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    /opt/homebrew/bin/stow -D $folder
    /opt/homebrew/bin/stow $folder
done

popd
